"""change base knowlegde and enviroment property

Revision ID: 0f4c14274621
Revises: dbd72e87c670
Create Date: 2026-02-04 14:20:43.590874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4c14274621'
down_revision: Union[str, Sequence[str], None] = 'dbd72e87c670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environment_models', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environment_models', 'is_active')
    # ### end Alembic commands ###
