"""add rouge detail table

Revision ID: cfc70616ded2
Revises: 30afad596eb3
Create Date: 2026-03-26 22:31:37.700191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc70616ded2'
down_revision: Union[str, Sequence[str], None] = '30afad596eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_evaluation_rouge_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_result_id', sa.Integer(), nullable=True),
    sa.Column('rouge_1_precision', sa.Float(), nullable=True),
    sa.Column('rouge_1_recall', sa.Float(), nullable=True),
    sa.Column('rouge_1_f1', sa.Float(), nullable=True),
    sa.Column('rouge_2_precision', sa.Float(), nullable=True),
    sa.Column('rouge_2_recall', sa.Float(), nullable=True),
    sa.Column('rouge_2_f1', sa.Float(), nullable=True),
    sa.Column('rouge_l_precision', sa.Float(), nullable=True),
    sa.Column('rouge_l_recall', sa.Float(), nullable=True),
    sa.Column('rouge_l_f1', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_result_id'], ['rag_evaluation_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_evaluation_rouge_details_id'), 'rag_evaluation_rouge_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_evaluation_rouge_details_id'), table_name='rag_evaluation_rouge_details')
    op.drop_table('rag_evaluation_rouge_details')
    # ### end Alembic commands ###
